import Head from 'next/head'
import AKAPNavbar from '../components/AKAPNavbar'

function Price ({ description, price }) {
  return (
    <div className='card-group'>
      <div className='card flex-row'>
        <img className='w-25' src='/images/eksekutif.png' alt='Card image cap' />
        <div className='card-body'>
          <p className='card-text'>
            {description}
          </p>
          <h5 className='card-title'>{price}</h5>
        </div>
      </div>
    </div>
  )
}

export default function Harga () {
  return (
    <>
      <Head>
        <title>PT. AKAP</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <AKAPNavbar />

      <div className='container'>
        <main>
          <h1 className='mt-4'>Daftar Bus</h1>

          <h2 className='mt-4'>Kelas Eksekutif</h2>
          <Price description='test' price='Rp300.000' />

          <h2 className='mt-4'>Kelas Bisnis</h2>
          <Price description='test' price='Rp200.000' />

          <h2 className='mt-4'>Kelas Ekonomi</h2>
          <Price description='test' price='Rp100.000' />

        </main>
      </div>
    </>
  )
}
