import Head from 'next/head'
import AKAPNavbar from '../components/AKAPNavbar'

function Price ({ description, price, imagePath }) {
  return (
    <div className='card-group'>
      <div className='card flex-row'>
        <img className='w-25' src={ imagePath } alt='Card image cap' />
        <div className='card-body'>
          <p className='card-text'>
            {description}
          </p>
          <h5 className='card-title'>{price}</h5>
        </div>
      </div>
    </div>
  )
}

export default function Harga () {
  return (
    <>
      <Head>
        <title>PT. AKAP</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <AKAPNavbar />

      <div className='container'>
        <main>
          <h1 className='mt-4'>Daftar Bus</h1>

          <h2 className='mt-4'>Kelas Eksekutif</h2>
          <Price
            description='Fasilitas bus AKAP kelas eksekutif kini semakin mewah, bahkan ada yang memiliki bangku pijat dan layanan makan layaknya first class.'
            price='Rp300.000'
            imagePath={'/images/eksekutif.png'}
            />

          <h2 className='mt-4'>Kelas Bisnis</h2>
          <Price
            description='Fasilitas bus AKAP kelas eksekutif kini semakin mewah, bahkan ada yang memiliki bangku pijat dan layanan makan layaknya first class.'
            price='Rp200.000'
            imagePath={'/images/bisnis.png'}
            />

          <h2 className='mt-4'>Kelas Ekonomi</h2>
          <Price
            description='Fasilitas bus AKAP kelas eksekutif kini semakin mewah, bahkan ada yang memiliki bangku pijat dan layanan makan layaknya first class.'
            price='Rp100.000'
            imagePath={'/images/ekonomi.png'}
            />
        </main>
      </div>
    </>
  )
}
