import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";
import AKAPNavbar from "../components/AKAPNavbar"

function BusArmadaInterior({ armadaDesc, interiorDesc }) {
  return (
    <div className="card-group">
      <div className="card">
        <img className="card-img-top" src="/images/eksekutif.png" alt="Card image cap"></img>
        <div className="card-body">
          <h5 className="card-title">Armada</h5>
          <p className="card-text">
            {armadaDesc}
          </p>
        </div>
      </div>
      <div className="card">
        <img className="card-img-top" src="/images/eksekutif.png" alt="Card image cap"></img>
        <div className="card-body">
          <h5 className="card-title">Interior</h5>
          <p className="card-text">
            {interiorDesc}
          </p>
        </div>
      </div>
    </div>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>PT. AKAP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AKAPNavbar />

      <div className="container">
        <main>
          <h1 className="mt-4">Daftar Bus</h1>

          <h2 className="mt-4">Kelas Eksekutif</h2>
          <BusArmadaInterior armadaDesc="test" interiorDesc="tset" />

          <h2 className="mt-4">Kelas Bisnis</h2>
          <BusArmadaInterior armadaDesc="test" interiorDesc="tset" />

          <h2 className="mt-4">Kelas Ekonomi</h2>
          <BusArmadaInterior armadaDesc="test" interiorDesc="tset" />

        </main>
      </div>
    </>
  );
}
