import Head from 'next/head'
import AKAPNavbar from '../components/AKAPNavbar'

function BusArmadaInterior ({ armadaDesc, interiorDesc, armadaImgPath, interiorImgPath }) {
  return (
    <div className='card-group'>
      <div className='card'>
        <img className='card-img-top' src={armadaImgPath} alt='Card image cap' />
        <div className='card-body'>
          <h5 className='card-title'>Armada</h5>
          <p className='card-text'>
            {armadaDesc}
          </p>
        </div>
      </div>
      <div className='card'>
        <img className='card-img-top' src={interiorImgPath} alt='Card image cap' />
        <div className='card-body'>
          <h5 className='card-title'>Interior</h5>
          <p className='card-text'>
            {interiorDesc}
          </p>
        </div>
      </div>
    </div>
  )
}

export default function Home () {
  return (
    <>
      <Head>
        <title>PT. AKAP</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <AKAPNavbar />

      <div className='container'>
        <main>
          <h1 className='mt-4'>Daftar Bus</h1>

          <h2 className='mt-4'>Kelas Eksekutif</h2>
          <BusArmadaInterior
            armadaImgPath={'/images/eksekutif.png'}
            interiorImgPath={'/images/eksekutif-interior.png'}
            armadaDesc='Kelas ternyaman untuk orang-orang yang ingin berkeliling di sekitar kota. Bus ini memiliki kapasitas penumpang maksimal sebanyak 40 orang.'
            interiorDesc='Interior premium' />

          <h2 className='mt-4'>Kelas Bisnis</h2>
          <BusArmadaInterior
            armadaImgPath={'/images/bisnis.png'}
            interiorImgPath={'/images/bisnis-interior.png'}
            armadaDesc='Kelas ternyaman untuk orang-orang yang ingin berkeliling di sekitar kota. Bus ini memiliki kapasitas penumpang maksimal sebanyak 40 orang.'
            interiorDesc='Interior premium' />

          <h2 className='mt-4'>Kelas Ekonomi</h2>
          <BusArmadaInterior
            armadaImgPath={'/images/ekonomi.png'}
            interiorImgPath={'/images/ekonomi-interior.png'}
            armadaDesc='Kelas ternyaman untuk orang-orang yang ingin berkeliling di sekitar kota. Bus ini memiliki kapasitas penumpang maksimal sebanyak 40 orang.'
            interiorDesc='Interior premium' />
        </main>
      </div>
    </>
  )
}
